services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./credits.yml:/app/credits.yml

  bot:
    build:
      dockerfile: Dockerfile
      context: ./bot
    volumes:
      - ./credits.yml:/app/credits.yml

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./secrets/db.env

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env_file: 
      - ./secrets/cloudflared.env

volumes:
  mongo-data: